{
 "title": "Copied main dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Hello Observability",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "Dashboard for a simple [Spring Boot](https://spring.io/guides/gs/spring-boot) application, based on [Hello Observability](https://github.com/adamquan/hello-observability), to demonstrate observability by collecting and correlating logs, metrics and traces with:\n- [Prometheus](https://prometheus.io/)\n- [Grafana Loki](https://grafana.com/oss/loki/)\n- [Grafana Tempo](https://grafana.com/oss/tempo/)\n \n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Service Up/Down",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "up{}\r\n", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (rate (http_server_requests_seconds_count[$__rate_interval])) * 60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[$__rate_interval]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=~\".+log\"} | json"
    }
   ]
  }
 ]
}