{
 "title": "tomcat-meins",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servlet requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(tomcat_servlet_request_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(instance) (tomcat_connections_current_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "avg by(instance) (tomcat_threads_busy_threads)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(instance) (tomcat_threads_current_threads)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}